<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Registration Management</title><style>
body{margin:0;background:#f5f7fb;color:#1f2a37;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}header{background:#153764;color:white;padding:18px 24px}.wrap{max-width:1240px;margin:0 auto;padding:22px 16px}.card{background:white;border:1px solid #d9dee8;border-radius:8px;padding:18px;box-shadow:0 4px 16px rgba(22,47,83,.05)}.bar{display:grid;grid-template-columns:1.5fr repeat(5,1fr);gap:10px;margin-bottom:14px}input,select{min-height:40px;border:1.5px solid #cbd3df;border-radius:6px;padding:8px 10px;font:inherit}.btn{border:0;border-radius:6px;padding:10px 14px;font-weight:900;text-decoration:none;display:inline-flex;background:#153764;color:white}.btn.light{background:white;color:#153764;border:1.5px solid #d9dee8}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid #edf0f5;font-size:13px;vertical-align:top}th{color:#153764}.status{padding:3px 8px;border-radius:999px;background:#eef3f9;color:#153764;font-weight:900;font-size:11px;white-space:nowrap}.notice{background:#e8f6ef;color:#237a4f;padding:10px 12px;border-radius:8px;margin-bottom:12px}.muted{color:#667085;font-size:12px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}@media(max-width:1000px){.bar{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr 1fr}table{display:block;overflow-x:auto}}@media(max-width:560px){.bar,.grid{grid-template-columns:1fr}}</style></head><body>
<header><h1>Registration Management</h1><p>Search, filter, verify, edit, note, export, and audit student registrations.</p></header>
<main class="wrap">@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif
<div class="card">
<form class="bar" method="GET">
<input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Name, email, parent email, passport, reference">
<select name="season_id"><option value="">All seasons</option>@foreach($seasons as $season)<option value="{{ $season->id }}" @selected(($filters['season_id']??'')==$season->id)>{{ $season->season_name }}</option>@endforeach</select>
<select name="subject_id"><option value="">All subjects</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected(($filters['subject_id']??'')==$subject->id)>{{ $subject->name }}</option>@endforeach</select>
<select name="payment_status"><option value="">Payment</option>@foreach(['unpaid','pending_payment','waiting_verification','paid','failed','refunded','cancelled'] as $status)<option value="{{ $status }}" @selected(($filters['payment_status']??'')===$status)>{{ $status }}</option>@endforeach</select>
<select name="status"><option value="">Registration</option>@foreach(['submitted','pending_payment','paid','completed','cancelled','expired','draft'] as $status)<option value="{{ $status }}" @selected(($filters['status']??'')===$status)>{{ $status }}</option>@endforeach</select>
<select name="document_status"><option value="">Document</option>@foreach(['missing','uploaded','pending_review','verified','invalid','reupload_requested'] as $status)<option value="{{ $status }}" @selected(($filters['document_status']??'')===$status)>{{ $status }}</option>@endforeach</select>
<select name="verification_status"><option value="">Verification</option>@foreach(['unverified','needs_review','verified','rejected'] as $status)<option value="{{ $status }}" @selected(($filters['verification_status']??'')===$status)>{{ $status }}</option>@endforeach</select>
<select name="receipt_status"><option value="">Receipt</option>@foreach(['pending_issue','issued','sent','failed','not_requested'] as $status)<option value="{{ $status }}" @selected(($filters['receipt_status']??'')===$status)>{{ $status }}</option>@endforeach</select>
<select name="needs_accommodations"><option value="">Accommodations</option><option value="1" @selected(($filters['needs_accommodations']??'')==='1')>Requested</option><option value="0" @selected(($filters['needs_accommodations']??'')==='0')>Not requested</option></select>
<select name="accommodation_status"><option value="">Accommodation Status</option>@foreach(['approved','pending','new'] as $status)<option value="{{ $status }}" @selected(($filters['accommodation_status']??'')===$status)>{{ $status }}</option>@endforeach</select>
<select name="period"><option value="">All periods</option><option value="main" @selected(($filters['period']??'')==='main')>Main</option><option value="late" @selected(($filters['period']??'')==='late')>Late</option></select>
<input type="date" name="date_from" value="{{ $filters['date_from'] ?? '' }}"><input type="date" name="date_to" value="{{ $filters['date_to'] ?? '' }}">
<button class="btn" type="submit">Filter</button>
</form>
<p class="muted">{{ $registrations->total() }} result(s)</p>
<form method="GET" action="{{ route('admin.student-registrations.export') }}" class="card">
@foreach(request()->except(['format','template','include_notes','mask_passport','school']) as $key => $value)
@if(is_scalar($value))<input type="hidden" name="{{ $key }}" value="{{ $value }}">@endif
@endforeach
<h2>Export Data</h2>
<div class="grid"><label>Format<select name="format"><option value="csv">CSV</option><option value="xlsx">Excel (.xlsx)</option></select></label><label>Template<select name="template"><option value="standard">Standard</option><option value="tpca">TPCA</option><option value="school">School</option></select></label><label>Document Status<select name="document_status"><option value="">Any</option>@foreach(['not_uploaded','uploaded','pending_review','verified','invalid','reupload_requested','replaced','deleted'] as $status)<option value="{{ $status }}">{{ $status }}</option>@endforeach</select></label><label>School<input name="school" value="{{ request('school') }}"></label></div>
<label><span><input type="checkbox" name="include_notes" value="1"> Include internal notes</span></label>
<label><span><input type="checkbox" name="mask_passport" value="1" checked> Mask passport numbers</span></label>
<button class="btn" type="submit">Create Export</button> <a class="btn light" href="{{ route('admin.exports.index') }}">Export History</a>
</form>
<table><thead><tr><th>Reference</th><th>Season</th><th>Student</th><th>Parent</th><th>Passport</th><th>School</th><th>Exams</th><th>Period</th><th>Payment</th><th>Registration</th><th>Submitted</th><th>Updated</th><th>Actions</th></tr></thead><tbody>
@foreach($registrations as $registration)<tr><td>{{ $registration->registration_number }}</td><td>{{ $registration->examSeason?->season_name ?? 'Legacy' }}</td><td>{{ $registration->student_full_name }}<br><span class="muted">{{ $registration->student_email }}</span></td><td>{{ $registration->contact?->parent_full_name }}<br><span class="muted">{{ $registration->contact?->parent_email }}</span></td><td>{{ $registration->passport_number }}</td><td>{{ $registration->school_name }}<br><span class="muted">Grade {{ $registration->grade_level }}</span></td><td>{{ $registration->exams_count }}</td><td>{{ $registration->registration_period_type ? ucfirst($registration->registration_period_type) : ($registration->late_fee_total > 0 ? 'Late' : 'Main') }}</td><td><span class="status">{{ $registration->payment_status }}</span></td><td><span class="status">{{ $registration->status }}</span></td><td>{{ optional($registration->submitted_at)->format('Y-m-d') }}</td><td>{{ $registration->updated_at->format('Y-m-d') }}</td><td><a class="btn light" href="{{ route('admin.student-registrations.show',$registration) }}">View</a> <a class="btn light" href="{{ route('admin.student-registrations.edit',$registration) }}">Edit</a></td></tr>@endforeach
</tbody></table>{{ $registrations->links() }}</div></main></body></html>
