<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ $registration->registration_number }}</title><style>
body{margin:0;background:#f5f7fb;color:#1f2a37;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}.wrap{max-width:1100px;margin:0 auto;padding:22px 16px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.card{background:white;border:1px solid #d9dee8;border-radius:8px;padding:20px;margin-bottom:14px;box-shadow:0 4px 16px rgba(22,47,83,.05)}h1,h2,h3{color:#153764}.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{border:0;border-radius:6px;padding:10px 14px;font-weight:900;text-decoration:none;display:inline-flex;background:#153764;color:white;cursor:pointer}.btn.light{background:white;color:#153764;border:1.5px solid #d9dee8}.btn.danger{background:#b42318}table{width:100%;border-collapse:collapse}td{padding:8px 0;border-bottom:1px solid #edf0f5;font-size:13px;vertical-align:top}td:first-child{width:34%;color:#667085}.timeline{border-left:3px solid #d9dee8;padding-left:14px}.timeline div{margin-bottom:12px}.notice{background:#e8f6ef;color:#237a4f;padding:10px 12px;border-radius:8px;margin-bottom:12px}label{display:flex;flex-direction:column;gap:6px;margin-bottom:10px;font-weight:800}input,textarea,select{border:1.5px solid #cbd3df;border-radius:6px;padding:9px 11px;font:inherit}textarea{min-height:74px}.note{background:#fbfcfe;border:1px solid #edf0f5;border-radius:8px;padding:12px;margin-bottom:10px}.status{display:inline-flex;border:1px solid #d9dee8;border-radius:999px;padding:4px 9px;background:#fbfcfe;font-weight:900}.mini{font-size:12px;color:#667085}@media(max-width:820px){.grid{grid-template-columns:1fr}}</style></head><body><main class="wrap">
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="card">{{ $errors->first() }}</div>@endif
<div class="card"><h1>{{ $registration->registration_number }}</h1><div class="actions"><a class="btn light" href="{{ route('admin.student-registrations.index') }}">Back</a><a class="btn light" href="{{ route('admin.student-registrations.edit',$registration) }}">Edit</a><a class="btn light" href="{{ route('admin.student-registrations.print',$registration) }}">Print</a><form method="POST" action="{{ route('admin.student-registrations.destroy',$registration) }}">@csrf @method('DELETE')<button class="btn danger" type="submit">Delete</button></form></div></div>
<div class="grid">
<div class="card"><h2>Student Information</h2><table><tr><td>Full name</td><td>{{ $registration->student_full_name }}</td></tr><tr><td>DOB</td><td>{{ optional($registration->date_of_birth)->format('Y-m-d') }}</td></tr><tr><td>Nationality</td><td>{{ $registration->nationality }}</td></tr><tr><td>Passport</td><td>{{ $registration->passport_number }}</td></tr><tr><td>Email</td><td>{{ $registration->student_email }}</td></tr><tr><td>Phone</td><td>{{ $registration->student_phone }}</td></tr></table></div>
<div class="card"><h2>School & Guardian</h2><table><tr><td>School</td><td>{{ $registration->school_name }}</td></tr><tr><td>Grade</td><td>{{ $registration->grade_level }}</td></tr><tr><td>Parent</td><td>{{ $registration->contact?->parent_full_name }}</td></tr><tr><td>Parent Email</td><td>{{ $registration->contact?->parent_email }}</td></tr><tr><td>Parent Phone</td><td>{{ $registration->contact?->parent_phone }}</td></tr><tr><td>Emergency</td><td>{{ $registration->contact?->emergency_contact_name }} / {{ $registration->contact?->emergency_contact_phone }}</td></tr></table></div>
<div class="card"><h2>Exam Selection</h2><table>@foreach($registration->exams as $exam)<tr><td>{{ $exam->name }}</td><td>{{ optional($exam->pivot->exam_date)->format('Y-m-d') }}<br>Exam NT$ {{ number_format($exam->pivot->exam_fee) }} / Service NT$ {{ number_format($exam->pivot->service_fee) }} / Late NT$ {{ number_format($exam->pivot->late_fee_snapshot) }}</td></tr>@endforeach<tr><td>Total</td><td>NT$ {{ number_format($registration->total_fee) }}</td></tr></table></div>
<div class="card"><h2>Payment & Documents</h2><table><tr><td>Payment Status</td><td>{{ $registration->payment_status }}</td></tr><tr><td>Amount</td><td>NT$ {{ number_format($registration->payment_amount ?: $registration->total_fee) }}</td></tr><tr><td>Method</td><td>{{ $registration->payment_method }}</td></tr><tr><td>Reference</td><td>{{ $registration->payment_reference }}</td></tr><tr><td>Payment Date</td><td>{{ optional($registration->payment_date)->format('Y-m-d') }}</td></tr><tr><td>Passport Status</td><td>{{ $registration->passport_upload_status }}</td></tr></table></div>
</div>
<div class="card"><h2>Verification</h2><table><tr><td>Status</td><td>{{ $registration->verification_status }}</td></tr><tr><td>Verified By</td><td>{{ $registration->verifier?->name }}</td></tr><tr><td>Verified At</td><td>{{ optional($registration->verified_at)->format('Y-m-d H:i') }}</td></tr><tr><td>Note</td><td>{{ $registration->verification_note }}</td></tr></table><form method="POST" action="{{ route('admin.student-registrations.verify',$registration) }}">@csrf<label>Status<select name="verification_status"><option value="verified">Verified</option><option value="needs_review">Needs Review</option><option value="rejected">Rejected</option><option value="unverified">Unverified</option></select></label><label>Verification Note<textarea name="verification_note"></textarea></label><button class="btn" type="submit">Update Verification</button></form></div>
<div class="card">
<h2>Passport Management</h2>
<div class="grid">
<div><table>
<tr><td>Status</td><td><span class="status">{{ $registration->passport_upload_status }}</span></td></tr>
<tr><td>Document UUID</td><td>{{ $registration->passport_document_uuid ?: 'Not assigned' }}</td></tr>
<tr><td>File</td><td>{{ $registration->passport_original_name ?: 'No file stored' }}</td></tr>
<tr><td>Type / Size</td><td>{{ $registration->passport_mime_type ?: '-' }} / {{ $registration->passport_file_size ? number_format($registration->passport_file_size / 1024, 1).' KB' : '-' }}</td></tr>
<tr><td>Uploaded</td><td>{{ optional($registration->passport_uploaded_at)->format('Y-m-d H:i') ?: '-' }}</td></tr>
<tr><td>Viewed / Downloaded</td><td>{{ optional($registration->passport_last_viewed_at)->format('Y-m-d H:i') ?: '-' }} / {{ optional($registration->passport_last_downloaded_at)->format('Y-m-d H:i') ?: '-' }}</td></tr>
<tr><td>Verification Note</td><td>{{ $registration->passport_verification_note ?: '-' }}</td></tr>
<tr><td>Invalid Reason</td><td>{{ $registration->passport_invalid_reason ?: '-' }}</td></tr>
<tr><td>Re-upload Reason</td><td>{{ $registration->passport_reupload_reason ?: '-' }} @if($registration->passport_reupload_deadline_at)<br><span class="mini">Deadline {{ $registration->passport_reupload_deadline_at->format('Y-m-d') }}</span>@endif</td></tr>
</table>@if($registration->passport_file_path)<p class="actions"><a class="btn light" href="{{ route('admin.student-registrations.passport.preview',$registration) }}" target="_blank">Preview</a><a class="btn light" href="{{ route('admin.student-registrations.passport.download',$registration) }}">Download</a></p>@endif</div>
<div>
<form method="POST" enctype="multipart/form-data" action="{{ route('admin.student-registrations.passport.replace',$registration) }}">@csrf<h3>Replace Passport</h3><label>New File<input type="file" name="passport" accept=".pdf,.jpg,.jpeg,.png" required></label><label>Reason<textarea name="reason" required></textarea></label><button class="btn" type="submit">Replace File</button></form>
<form method="POST" action="{{ route('admin.student-registrations.passport.status',$registration) }}">@csrf<h3>Mark Status</h3><label>Status<select name="status"><option value="verified">Valid</option><option value="invalid">Invalid</option></select></label><label>Verification Note<textarea name="verification_note"></textarea></label><label>Invalid Reason<textarea name="invalid_reason"></textarea></label><button class="btn" type="submit">Update Passport</button></form>
</div>
</div>
<form method="POST" action="{{ route('admin.student-registrations.passport.reupload',$registration) }}">@csrf<h3>Request Re-upload</h3><div class="grid"><label>Reason<textarea name="reason" required></textarea></label><label>Deadline<input type="date" name="deadline" required></label></div><button class="btn" type="submit">Send Re-upload Email</button></form>
</div>
<div class="grid">
<div class="card"><h2>Internal Notes</h2><form method="POST" action="{{ route('admin.student-registrations.notes.store',$registration) }}">@csrf<label>Type<select name="note_type">@foreach(['general','payment','document','student_contact','school_communication','issue','follow_up'] as $type)<option value="{{ $type }}">{{ $type }}</option>@endforeach</select></label><label>Note<textarea name="note" required></textarea></label><label><span><input type="checkbox" name="is_pinned" value="1"> Pin note</span></label><button class="btn" type="submit">Add Note</button></form>@foreach($registration->adminNotes->sortByDesc('created_at') as $note)<div class="note"><strong>{{ $note->note_type }}</strong> @if($note->is_pinned)<span>PINNED</span>@endif<br>{{ $note->note }}<br><small>{{ $note->author?->name }} / {{ $note->created_at->format('Y-m-d H:i') }}</small></div>@endforeach</div>
<div class="card"><h2>Activity Log</h2><div class="timeline">@foreach($registration->auditLogs->sortByDesc('performed_at') as $log)<div><strong>{{ $log->action }}</strong> {{ $log->field_name }}<br><small>{{ $log->old_value }} -> {{ $log->new_value }}</small><br><small>{{ $log->performed_at->format('Y-m-d H:i') }} / {{ $log->reason }}</small></div>@endforeach @foreach($registration->histories as $history)<div><strong>{{ $history->to_status }}</strong><br>{{ $history->note }}<br><small>{{ $history->created_at->format('Y-m-d H:i') }}</small></div>@endforeach</div></div>
</div>
</main></body></html>
