<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>AP Exam Subject</title><style>
body{margin:0;background:#f5f7fb;color:#1f2a37;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}.wrap{max-width:920px;margin:0 auto;padding:22px 16px}.card{background:white;border:1px solid #d9dee8;border-radius:8px;padding:20px;box-shadow:0 4px 16px rgba(22,47,83,.05)}h1{color:#153764}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}label{display:flex;flex-direction:column;gap:6px;font-size:13px;font-weight:800}input,select,textarea{min-height:40px;border:1.5px solid #cbd3df;border-radius:6px;padding:9px 11px;font:inherit}textarea{min-height:90px}.btn{border:0;border-radius:6px;padding:10px 14px;font-weight:900;text-decoration:none;display:inline-flex;background:#153764;color:white}.light{background:white;color:#153764;border:1.5px solid #d9dee8}.error{background:#fff0ee;color:#b42318;padding:10px 12px;border-radius:8px;margin-bottom:12px}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style></head><body><main class="wrap">
@if($errors->any())<div class="error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card"><h1>{{ $subject->exists ? 'Edit' : 'Add' }} AP Exam Subject</h1><form method="POST" action="{{ $subject->exists ? route('admin.ap-exam-subjects.update',$subject) : route('admin.ap-exam-subjects.store') }}">@csrf @if($subject->exists)@method('PUT')@endif
<div class="grid">
<label>Exam Season<select name="exam_season_id"><option value="">Legacy / no season</option>@foreach($seasons ?? [] as $season)<option value="{{ $season->id }}" @selected((string) old('exam_season_id',$subject->exam_season_id)===(string) $season->id)>{{ $season->season_name }} ({{ $season->exam_year }})</option>@endforeach</select></label>
<label>Exam Code<input name="code" value="{{ old('code',$subject->code) }}" required></label><label>Exam Name<input name="name" value="{{ old('name',$subject->name) }}" required></label>
<label>Category<input name="category" value="{{ old('category',$subject->category) }}" required></label><label>Status<select name="status">@foreach(['draft','not_open','open','limited','full','closed','cancelled','disabled'] as $status)<option value="{{ $status }}" @selected(old('status',$subject->status)===$status)>{{ $status }}</option>@endforeach</select></label>
<label>Description<textarea name="description">{{ old('description',$subject->description) }}</textarea></label><label>Location<input name="location" value="{{ old('location',$subject->location) }}"></label>
<label>Exam Date<input type="date" name="exam_date" value="{{ old('exam_date', optional($subject->exam_date)->format('Y-m-d')) }}"></label><label>Timezone<input name="timezone" value="{{ old('timezone',$subject->timezone ?: 'Asia/Taipei') }}" required></label>
<label>Start Time<input type="time" name="start_time" value="{{ old('start_time', $subject->start_time ? substr($subject->start_time,0,5) : '') }}"></label><label>End Time<input type="time" name="end_time" value="{{ old('end_time', $subject->end_time ? substr($subject->end_time,0,5) : '') }}"></label>
<label>Quota<input type="number" name="quota" value="{{ old('quota',$subject->quota) }}" min="0"></label><label>Sort Order<input type="number" name="sort_order" value="{{ old('sort_order',$subject->sort_order ?? 0) }}" required min="0"></label>
<label>Exam Fee<input type="number" name="exam_fee" value="{{ old('exam_fee',$subject->exam_fee ?? 0) }}" required min="0"></label><label>Service Fee<input type="number" name="service_fee" value="{{ old('service_fee',$subject->service_fee ?? 0) }}" required min="0"></label>
<label>Late Registration Fee<input type="number" name="late_registration_fee" value="{{ old('late_registration_fee',$subject->late_registration_fee ?? 0) }}" required min="0"></label><label>Currency<input name="currency" value="{{ old('currency',$subject->currency ?: 'NTD') }}" required></label>
<label>Registration Open<input type="datetime-local" name="registration_open_at" value="{{ old('registration_open_at', optional($subject->registration_open_at)->format('Y-m-d\TH:i')) }}"></label><label>Registration Close<input type="datetime-local" name="registration_close_at" value="{{ old('registration_close_at', optional($subject->registration_close_at)->format('Y-m-d\TH:i')) }}"></label>
<label>Late Start<input type="datetime-local" name="late_registration_start_at" value="{{ old('late_registration_start_at', optional($subject->late_registration_start_at)->format('Y-m-d\TH:i')) }}"></label><label>Late End<input type="datetime-local" name="late_registration_end_at" value="{{ old('late_registration_end_at', optional($subject->late_registration_end_at)->format('Y-m-d\TH:i')) }}"></label>
<label><span>Active</span><select name="is_active"><option value="1" @selected(old('is_active',$subject->is_active)!==false)>Yes</option><option value="0" @selected(old('is_active',$subject->is_active)===false)>No</option></select></label>
</div><p><button class="btn" type="submit">Save</button> <a class="btn light" href="{{ route('admin.ap-exam-subjects.index') }}">Cancel</a></p></form></div></main></body></html>
