<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ __('admin_dashboard.title') }}</title><style>
body{margin:0;background:#f5f7fb;color:#1f2a37;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}header{background:#153764;color:white;padding:18px 24px}.wrap{max-width:1180px;margin:0 auto;padding:22px 16px}.top{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}.btn{border:0;border-radius:6px;padding:10px 14px;background:white;color:#153764;text-decoration:none;font-weight:900;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.card{background:white;border:1px solid #d9dee8;border-radius:8px;padding:18px;box-shadow:0 4px 16px rgba(22,47,83,.05)}.metric strong{display:block;color:#153764;font-size:28px}.metric span{color:#667085;font-size:12px}.filters{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin:16px 0}.filters input,.filters select{min-height:40px;border:1.5px solid #cbd3df;border-radius:6px;padding:8px 10px;font:inherit}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid #edf0f5;font-size:13px}th{color:#153764}.bar{height:8px;background:#edf0f5;border-radius:999px;overflow:hidden}.bar i{display:block;height:100%;background:#153764}.chart{display:flex;align-items:end;gap:8px;height:130px}.chart div{flex:1;background:#153764;border-radius:6px 6px 0 0;min-height:4px}.muted{color:#667085}@media(max-width:900px){.grid,.filters{grid-template-columns:1fr 1fr}table{display:block;overflow-x:auto}}@media(max-width:560px){.grid,.filters{grid-template-columns:1fr}}</style></head><body><header><div class="top"><div><h1>{{ __('admin_dashboard.title') }}</h1><p>AP Exam Registration Platform</p></div><form method="POST" action="{{ route('admin.logout') }}">@csrf<button class="btn" type="submit">Logout</button></form></div></header><main class="wrap">
<form class="filters" method="GET"><select name="period"><option value="">All periods</option><option value="main" @selected(($filters['period']??'')==='main')>Main</option><option value="late" @selected(($filters['period']??'')==='late')>Late</option></select><input type="date" name="date_from" value="{{ $filters['date_from'] ?? '' }}"><input type="date" name="date_to" value="{{ $filters['date_to'] ?? '' }}"><select name="status"><option value="">All statuses</option>@foreach(['submitted','pending_payment','paid','completed','cancelled','expired'] as $status)<option value="{{ $status }}" @selected(($filters['status']??'')===$status)>{{ $status }}</option>@endforeach</select><select name="subject_id"><option value="">All subjects</option>@foreach($subjects as $subject)<option value="{{ $subject->id }}" @selected(($filters['subject_id']??'')==$subject->id)>{{ $subject->name }}</option>@endforeach</select><button class="btn" style="background:#153764;color:white" type="submit">Apply Filters</button></form>
<section class="grid">
@foreach([
__('admin_dashboard.total_registrations')=>[$totals['registrations'],'Today '.$totals['today'].' / Week '.$totals['week'].' / Month '.$totals['month']],
__('admin_dashboard.pending_payment')=>[$totals['pending_payment'],'Submitted or waiting verification'],
__('admin_dashboard.paid_registrations')=>[$totals['paid'],'Collected NT$ '.number_format($totals['total_revenue'])],
__('admin_dashboard.incomplete_registrations')=>[$totals['incomplete'],'Draft or missing required items'],
__('admin_dashboard.late_registrations')=>[$totals['late'],'Late fee NT$ '.number_format($totals['late_fee_revenue'])],
__('admin_dashboard.total_revenue')=>['NT$ '.number_format($totals['total_revenue']),'Paid registrations only'],
__('admin_dashboard.service_fee_revenue')=>['NT$ '.number_format($totals['service_fee_revenue']),'Fapiao eligible service fee'],
__('admin_dashboard.passport_pending_review')=>[$totals['passport_pending_review'],'Uploaded passports awaiting document review'],
'Pending Docs'=>[$totals['pending_documents'],'Missing, invalid, or re-upload requested'],
'Waiting Verification'=>[$totals['waiting_verification'],'Needs admin review before completion'],
'Receipt Pending'=>[$totals['receipt_pending'],'Fapiao/receipt requests to issue'],
'Quota Watch'=>[$totals['subjects_near_quota'],'Subjects with 5 or fewer seats left'],
] as $title=>$data)<div class="card metric"><span>{{ $title }}</span><strong>{{ $data[0] }}</strong><span>{{ $data[1] }}</span></div>@endforeach
</section>
<section class="card" style="margin-top:14px"><h2>Operations Queue</h2><table><thead><tr><th>Queue</th><th>Count</th><th>What to check</th></tr></thead><tbody>@foreach($operations as $item)<tr><td>{{ $item['label'] }}</td><td>{{ $item['count'] }}</td><td>{{ $item['hint'] }}</td></tr>@endforeach</tbody></table></section>
<section class="card" style="margin-top:14px"><h2>Registrations by Day</h2><div class="chart">@php($max=max($byDay ?: [1])) @foreach($byDay ?: ['No data'=>0] as $day=>$count)<div title="{{ $day }}: {{ $count }}" style="height:{{ max(4,($count/$max)*120) }}px"></div>@endforeach</div></section>
<section class="card" style="margin-top:14px"><h2>{{ __('admin_dashboard.exam_subject_summary') }}</h2><table><thead><tr><th>Subject</th><th>Selected</th><th>Quota</th><th>Remaining</th><th>Status</th><th>Exam Fee</th><th>Service Fee</th><th>Late Fee</th></tr></thead><tbody>@foreach($bySubject as $row)<tr><td>{{ $row['name'] }} ({{ $row['code'] }})</td><td>{{ $row['selected_count'] }}</td><td>{{ $row['quota'] ?? '∞' }}</td><td>{{ $row['remaining'] ?? '∞' }}<div class="bar"><i style="width:{{ $row['quota'] ? min(100,($row['selected_count']/$row['quota'])*100) : 0 }}%"></i></div></td><td>{{ $row['status'] }}</td><td>NT$ {{ number_format($row['exam_fee_total']) }}</td><td>NT$ {{ number_format($row['service_fee_total']) }}</td><td>NT$ {{ number_format($row['late_fee_total']) }}</td></tr>@endforeach</tbody></table></section>
<section class="card" style="margin-top:14px"><h2>Payment Status Breakdown</h2><table><tbody>@foreach($byStatus as $status=>$count)<tr><td>{{ $status }}</td><td>{{ $count }}</td></tr>@endforeach</tbody></table></section>
</main></body></html>
