<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ __('payment.title') }}</title><style>
body{margin:0;background:#f5f7fb;color:#1f2a37;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}.wrap{max-width:920px;margin:0 auto;padding:28px 16px}.card{background:white;border:1px solid #d9dee8;border-radius:8px;padding:22px;margin-bottom:14px;box-shadow:0 4px 16px rgba(22,47,83,.05)}h1,h2{color:#153764}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}table{width:100%;border-collapse:collapse}td{padding:8px 0;border-bottom:1px solid #edf0f5;font-size:13px}td:first-child{color:#667085;width:38%}.btn{display:inline-flex;background:#153764;color:white;border:0;text-decoration:none;padding:11px 16px;border-radius:6px;font-weight:900;cursor:pointer}.btn.light{background:white;color:#153764;border:1.5px solid #d9dee8}.notice{background:#e8f6ef;color:#237a4f;padding:10px 12px;border-radius:8px;margin-bottom:12px}label{display:flex;flex-direction:column;gap:6px;font-weight:800;margin-bottom:10px}input{border:1.5px solid #cbd3df;border-radius:6px;padding:9px 11px}@media(max-width:720px){.grid{grid-template-columns:1fr}}</style></head><body><main class="wrap">
@if(session('status'))<div class="notice">{{ session('status') }}</div>@endif @if($errors->any())<div class="card">{{ $errors->first() }}</div>@endif
<div class="card"><h1>{{ __('payment.title') }}</h1><p>{{ __('payment.manual_instruction') }}</p><table><tr><td>Registration</td><td>{{ $registration->registration_number }}</td></tr><tr><td>Student</td><td>{{ $registration->student_full_name }}</td></tr><tr><td>Status</td><td>{{ $payment->payment_status }}</td></tr><tr><td>Payment Reference</td><td>{{ $payment->payment_reference }}</td></tr><tr><td>Amount</td><td>{{ $payment->currency }} {{ number_format($payment->grand_total) }}</td></tr><tr><td>Deadline</td><td>{{ optional($payment->payment_deadline_at)->format('Y-m-d H:i') }}</td></tr></table></div>
<div class="grid">
<div class="card"><h2>Bank Transfer</h2><table><tr><td>Bank</td><td>{{ $setting->bank_name }}</td></tr><tr><td>Bank Code</td><td>{{ $setting->bank_code }}</td></tr><tr><td>Account Name</td><td>{{ $setting->account_name }}</td></tr><tr><td>Account Number</td><td>{{ $setting->account_number }}</td></tr><tr><td>Note</td><td>{{ $setting->manual_instruction }}</td></tr></table></div>
<div class="card"><h2>Upload Proof</h2><form method="POST" enctype="multipart/form-data" action="{{ route('payments.proof.upload',$payment) }}">@csrf<label>Proof of Payment<input type="file" name="proof" accept=".pdf,.jpg,.jpeg,.png" required></label><button class="btn" type="submit">Upload Proof</button></form><p><a class="btn light" href="{{ route('payments.gateway.start',$payment) }}">Pay by Taiwan Gateway</a></p></div>
</div>
</main></body></html>
