<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Exam Season</title><style>
body{margin:0;background:#f5f7fb;color:#1f2a37;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}.wrap{max-width:960px;margin:0 auto;padding:22px 16px}.card{background:white;border:1px solid #d9dee8;border-radius:8px;padding:20px;box-shadow:0 4px 16px rgba(22,47,83,.05)}h1{color:#153764}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}label{display:flex;flex-direction:column;gap:6px;font-size:13px;font-weight:800}input,select,textarea{min-height:40px;border:1.5px solid #cbd3df;border-radius:6px;padding:9px 11px;font:inherit}textarea{min-height:90px}.btn{border:0;border-radius:6px;padding:10px 14px;font-weight:900;text-decoration:none;display:inline-flex;background:#153764;color:white}.light{background:white;color:#153764;border:1.5px solid #d9dee8}.error{background:#fff0ee;color:#b42318;padding:10px 12px;border-radius:8px;margin-bottom:12px}@media(max-width:760px){.grid{grid-template-columns:1fr}}</style></head><body><main class="wrap">
@if($errors->any())<div class="error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card"><h1>{{ $season->exists ? 'Edit' : 'Create' }} Exam Season</h1><form method="POST" action="{{ $season->exists ? route('admin.exam-seasons.update',$season) : route('admin.exam-seasons.store') }}">@csrf @if($season->exists)@method('PUT')@endif
<div class="grid">
<label>Season Name<input name="season_name" value="{{ old('season_name',$season->season_name) }}" required></label><label>Academic Year<input name="academic_year" value="{{ old('academic_year',$season->academic_year) }}" required></label>
<label>Exam Year<input type="number" name="exam_year" value="{{ old('exam_year',$season->exam_year) }}" required></label><label>Status<select name="status">@foreach(['draft','not_open','open','late_registration','closed','archived'] as $status)<option value="{{ $status }}" @selected(old('status',$season->status)===$status)>{{ $status }}</option>@endforeach</select></label>
<label>Main Start<input type="datetime-local" name="main_registration_start_at" value="{{ old('main_registration_start_at', optional($season->main_registration_start_at)->format('Y-m-d\TH:i')) }}"></label><label>Main End<input type="datetime-local" name="main_registration_end_at" value="{{ old('main_registration_end_at', optional($season->main_registration_end_at)->format('Y-m-d\TH:i')) }}"></label>
<label>Late Start<input type="datetime-local" name="late_registration_start_at" value="{{ old('late_registration_start_at', optional($season->late_registration_start_at)->format('Y-m-d\TH:i')) }}"></label><label>Late End<input type="datetime-local" name="late_registration_end_at" value="{{ old('late_registration_end_at', optional($season->late_registration_end_at)->format('Y-m-d\TH:i')) }}"></label>
<label>Timezone<input name="timezone" value="{{ old('timezone',$season->timezone ?: 'Asia/Taipei') }}" required></label><label>Currency<input name="currency" value="{{ old('currency',$season->currency ?: 'NTD') }}" required></label>
<label>Default Service Fee<input type="number" name="default_service_fee" value="{{ old('default_service_fee',$season->default_service_fee ?? 0) }}" required min="0"></label><label>Default Late Fee<input type="number" name="default_late_fee" value="{{ old('default_late_fee',$season->default_late_fee ?? 0) }}" required min="0"></label>
<label>Public Status Message<textarea name="public_status_message">{{ old('public_status_message',$season->public_status_message) }}</textarea></label><label>Notes<textarea name="notes">{{ old('notes',$season->notes) }}</textarea></label>
<label>Close Reason<textarea name="close_reason">{{ old('close_reason',$season->close_reason) }}</textarea></label><label>Reopen Reason<textarea name="reopen_reason">{{ old('reopen_reason',$season->reopen_reason) }}</textarea></label>
<label><span>Active Season</span><select name="is_active"><option value="0" @selected(! old('is_active',$season->is_active))>No</option><option value="1" @selected(old('is_active',$season->is_active))>Yes</option></select></label>
</div><p><button class="btn" type="submit">Save</button> <a class="btn light" href="{{ route('admin.exam-seasons.index') }}">Cancel</a></p></form></div></main></body></html>
